### ISSUE TITLE
BackgroundJob.ContinueWith() has an error in the 2.1.6-preview

### ISSUE THREAD

**Issue by zxkurama** [stulzq/Hangfire.MySql.Core#12]
{Hangfire.BackgroundJobClientException: Background job creation failed. See inner exception for details. ---> System.MissingMethodException: Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.
   at Hangfire.States.AwaitingState.SerializeData()
   at Hangfire.MySql.Core.MySqlWriteOnlyTransaction.<>c__DisplayClass6_0.<SetJobState>b__0(MySqlConnection x)
   at Hangfire.MySql.Core.MySqlWriteOnlyTransaction.<Commit>b__29_0(MySqlConnection connection)
   at Hangfire.MySql.Core.MySqlStorage.<>c__DisplayClass19_0.<UseTransaction>b__0(MySqlConnection connection)
   at Hangfire.MySql.Core.MySqlStorage.UseConnection[T](Func`2 func)
   at Hangfire.MySql.Core.MySqlStorage.UseTransaction(Action`1 action)
   at Hangfire.Client.CoreBackgroundJobFactory.Create(CreateContext context)
   at Hangfire.Client.BackgroundJobFactory.<>c__DisplayClass7_0.<CreateWithFilters>b__0()
   at Hangfire.Client.BackgroundJobFactory.InvokeClientFilter(IClientFilter filter, CreatingContext preContext, Func`1 continuation)
   at Hangfire.Client.BackgroundJobFactory.Create(CreateContext context)
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   --- End of inner exception stack trace ---
   at Hangfire.BackgroundJobClient.Create(Job job, IState state)
   at Hangfire.BackgroundJob.ContinueWith[T](String parentId, Expression`1 methodCall, JobContinuationOptions options)

**Comment by dnguyen07** [comment]
Hi, 
I also have the same issue... 

Would be nice to have an explanation.

Thanks in advance!
