### ISSUE TITLE
error。。。

### ISSUE THREAD

**Issue by zsy619** [stulzq/Hangfire.MySql.Core#24]
MySql.Data.MySqlClient.MySqlException (0x80004005): The table does not comply with the requirements by an external plugin.
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
at Dapper.SqlMapper.ExecuteCommand(IDbConnection cnn, CommandDefinition& command, Action2 paramReader) in C:\projects\dapper\Dapper\SqlMapper.cs:line 2836 at Dapper.SqlMapper.ExecuteImpl(IDbConnection cnn, CommandDefinition& command) in C:\projects\dapper\Dapper\SqlMapper.cs:line 570 at Dapper.SqlMapper.Execute(IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Nullable1 commandTimeout, Nullable1 commandType) in C:\projects\dapper\Dapper\SqlMapper.cs:line 443 at Hangfire.MySql.Core.MySqlDistributedLock.AcquireLock(String resource, TimeSpan timeout) in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlDistributedLock.cs:line 56 at Hangfire.MySql.Core.MySqlDistributedLock.Acquire() in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlDistributedLock.cs:line 93 at Hangfire.MySql.Core.MySqlStorageConnection.AcquireDistributedLock(String resource, TimeSpan timeout) in E:\sms2018\Hangfire.MySql.Core\Hangfire.MySql\MySqlStorageConnection.cs:line 35 at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, String recurringJobId, TimeSpan timeout) at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, RecurringJobOptions options) at Hangfire.RecurringJobManagerExtensions.AddOrUpdate(IRecurringJobManager manager, String recurringJobId, Job job, String cronExpression, TimeZoneInfo timeZone, String queue) at Hangfire.RecurringJob.AddOrUpdate(Expression1 methodCall, String cronExpression, TimeZoneInfo timeZone, String queue)
at TxSms.Timed.Startup.<>c.b__1_81(HttpContext context) in E:\sms2018\TxSms.DP\src\TxSms.Timed\Startup.cs:line 464

**Comment by zsy619** [comment]
private int AcquireLock(string resource, TimeSpan timeout)
        {
            return
                _connection
                    .Execute(
                        $"INSERT INTO {_options.TablePrefix}_DistributedLock (Resource, CreatedAt) " +
                        "  SELECT @resource, @now " +
                        "  FROM dual " +
                        "  WHERE NOT EXISTS ( " +
                        $"  		SELECT * FROM {_options.TablePrefix}_DistributedLock " +
                        "     	WHERE Resource = @resource " +
                        "       AND CreatedAt > @expired)", 
                        new
                        {
                            resource,
                            now = DateTime.UtcNow, 
                            expired = DateTime.UtcNow.Add(timeout.Negate())
                        });
        }


请教一下，这个方法是什么作用，而且这个表dual在库里也不存在

**Comment by zsy619** [comment]
@stulzq 数据库驱动使用mysql.data

**Comment by stulzq** [comment]
What version is the component used and what version is the database used?
